---
title: "Data Exploration"
author: "Elise Keppel"
date: "10/27/2021"
output: pdf_document
filename: "Data exploration"
---

```{r setup, include=FALSE, message = FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = F)
source("R/0 Setup.R")

```

```{r load spatial files, results = FALSE}
# ----------------- LOAD SPATIAL FILES --------------------------------
# bc coast for plotting
if(!exists("coast")){
coast <- sf::st_read(dsn = "shapefiles", layer = "BC_coast_UTM9")
}

if(!exists("canada_shp")){
canada_shp <- st_read(dsn = "shapefiles", "CanadianEEZ") %>%
  st_transform(crs = 4326)
}
if(!exists("D")){
d <- st_read("shapefiles/less_than_5m.shp") %>% st_transform(crs = 4326)
}
coord <- ggplot2::coord_sf(xlim = c(-125.5, -123), ylim = c(48.1, 49.5), crs = sf::st_crs(4326)) 

# create bathymetric layer
bathy <- getNOAA.bathy(-125.5, -122.5,48.1, 49.5,res=1) %>% 
  fortify(bathy) 
bathy$z[which(bathy$z >= 0)] <- 0
col <- rev(RColorBrewer::brewer.pal(9L, "Blues")[4:7])
col_ramp <- colorRampPalette(col)


g <- ggplot() + 
  geom_raster(aes(x=x,y=y,fill = z), data = bathy) +  labs(fill = "Depth (m)") +
  scale_fill_gradientn(colours = col_ramp(20)) +
  ggnewscale::new_scale("fill") +
  # geom_contour(data = b, 
  #              aes(x=X, y=Y, z=PID),
  #              breaks=c(-250),
  #              size=c(0.6),
  #              colour="grey")+
  geom_sf(data = coast, stroke = 0.05, fill = "light yellow", colour = "grey 60")+
  geom_sf(data = canada_shp, colour = "red", fill = NA, linetype = "solid") 

```

## Summary of survey data up to Oct 2021
```{r load survey data, results = FALSE}
single <- F
all_effort <- load_effort(2021, 10, single)
all_effort_lines <- get_effort_lines(all_effort)
all_ap_sf <- load_sightings(2021, 10, single)
all_ap_sf%<>% arrange(year, month) 
lev <- unique(all_ap_sf$SurveyID )
all_ap_sf$SurveyID %<>% factor(levels = lev)
all_ap_sf$season %<>% factor(levels = c("Winter", "Spring", "Summer", "Fall"))
```
Total distance surveyed = `r round(sum(st_length(all_effort_lines))/1000) %>% as.numeric()` km


```{r summarise survey distance}

# l <- all_effort_lines %>% mutate(length = st_length(geometry)) %>%
#   group_by(Year = year, Month = factor(month.abb[month], levels = month.abb[1:12])) %>% 
#   summarise(total_survey_length_km = sum(length/1000))
# sum(st_length(all_effort_lines))

x <- all_effort_lines %>% mutate(length = st_length(geometry))
y <- x %>% as.data.frame() %>% filter(!is.na(length)) %>% transmute(Year = year, Month= month_abb, length = as.numeric(length)) %>%
  group_by(Year, Month) %>% 
  summarise(total_survey_length_km = round(sum(length/1000)))
# total number of survey days and total count cetacean sightings; days on effort per survey
e1 <- all_effort %>% filter(Status == "ON") %>%
  dplyr::group_by(Year = year(GpsT), Month = factor(month.abb[month(GpsT)], levels = month.abb[1:12])) %>% 
  dplyr::summarise("# survey days" = n_distinct(day(GpsT)))
e2 <- plyr::join(y, e1)
e2 %>% kableExtra::kable()
```

```{r summarise survey data, results = F}
s1 <- all_ap_sf %>% dplyr::group_by(Year = year(time_index), Month = factor(month.abb[month(time_index)], levels = month.abb[1:12])) %>%
  dplyr::summarise(" field_days" = (max(day(time_index)) - min(day(time_index)) + 1),  
                   "# transects" = (n_distinct(TransectID)),
                   "# sightings" = n(), 
                   "# individuals" = sum(BestNumber))
# s2 <- all_ap_sf %>%  dplyr::group_by(Species, season, year) %>%
#   dplyr::summarise("# sightings" = n(), "# individuals" = sum(BestNumber))

# counts by species in each survey
# s2 <- all_ap_sf %>%  dplyr::group_by(year, month, Species) %>%
#   dplyr::summarise(number_sightings = n(), number_indivduals = sum(BestNumber))

# counts by species in all surveys
s3 <- all_ap_sf %>%  dplyr::group_by(Species) %>%
  dplyr::summarise( "# sightings" = n(), "# individuals" = sum(BestNumber), "Mean grp size" = round(mean(BestNumber), 1))

s5 <- all_ap_sf %>% as.data.frame() %>% dplyr::group_by(Species, Year = year(time_index), Month = factor(month.abb[month(time_index)], levels = month.abb[1:12]), season) %>%
  dplyr::summarise(sgt = as.numeric(n()), indivs = as.numeric(sum(BestNumber))) %>% as.data.frame()

s6 <- plyr::join(y, s5, by=c("Year", "Month")) %>% 
  group_by(Species, Season = season, Year) %>% 
  summarise(sgt = sum(sgt), indivs = sum(indivs), total_survey_length_km = sum(total_survey_length_km),
            sgt_per_100_km_effort = round(sgt/total_survey_length_km*100)) %>% 
  dplyr::transmute(Species, Year, Season, sgt, indivs, 
                   srv_km = total_survey_length_km, sgt_per_100_km_effort) %>%
  ungroup() %>% as.data.frame() %>% 
  mutate(sgt_p_100k_eff = if_else(
    sgt_per_100_km_effort < 1, "< 1",
    as.character(sgt_per_100_km_effort))) %>% dplyr::select(-sgt_per_100_km_effort) %>% 
arrange(Species, Season, Year)
```





```{r survey summary}
s1 %>% as.data.frame() %>% dplyr::select(-geometry) %>% kableExtra::kable()
s3 %>% as.data.frame() %>% dplyr::select(-geometry) %>% kableExtra::kable()
s6 %>% kableExtra::kable()

```

```{r get_transect_plot, include = F, message = F, results = F}
{Save = F
  single_survey <- F
  incidentals <-  F
  hydrophone <- F
  sightings_only <- F
  # source(file.path(cemore,"developing/plot_survey.R"))
  source(file.path("R/plot_survey.R"))
}
```
```{r plot_all_transects}
g
```

# Beaufort conditions
```{r plot_beaufort_conditions}
all_effort_lines_sum <- all_effort_lines %>% mutate(length_km = as.numeric(st_length(geometry))/1000) %>% 
  as.data.frame() %>% mutate(Bf = factor(Bf, levels = c(0,1,2,3,4,5)))
suppressMessages(ggplot()) +
  geom_boxplot(data = all_effort_lines_sum, aes(Bf, length_km)) #+
  scale_y_discrete(labels = c(0,1,2,3,4,5))

col_bf <- rev(RColorBrewer::brewer.pal(11L, "Spectral")[2:11])
col_ramp_bf <- colorRampPalette(col_bf)
g <- suppressMessages(ggplot()) +
  geom_sf(data = coast, stroke = 0.05, fill = "light yellow", colour = "grey 60")+
  geom_sf(data = all_effort_lines, stroke = 2, aes(colour = factor(Bf))) +
  scale_colour_manual('Beaufort', values = col_ramp_bf(6)) +
    coord
g
g + facet_wrap(~factor(season, levels = c("Winter", "Spring", "Summer", "Fall")))
```

# Species Sightings
## Plot Harbour Porpoise sightings
```{r hp, echo=FALSE}
all_ap_sf %<>% mutate(Count =case_when(
  BestNumber == 1 ~ "1",
  BestNumber %in% c(2:5) ~ "2:5",
  BestNumber >5 ~ ">5"
) %>% factor(levels = c("1", "2:5", ">5")))

# make bathy legend
b_leg <- ggplot() +
  geom_raster(aes(x=x,y=y,fill = z), data = bathy) +  labs(fill = "Depth (m)") +
  scale_fill_gradientn(colours = col_ramp(20)) +
  theme(legend.position = "bottom") +
  guides(fill = guide_colorbar(title.position = "left", vjust = 10))
leg1 <- gtable_filter(ggplot_gtable(ggplot_build(b_leg)), "guide-box") 
leg1Grob <- grobTree(leg1)

sp <- "Harbour"
ap_sf <- all_ap_sf %>% filter(Species %like% sp)
ap_sf$Species %<>% droplevels()
# to order legend symbols consistently
sp <- unique(c(levels(ap_sf$Species)))

base_map <- ggplot() +
  geom_raster(aes(x=x,y=y,fill = z), data = bathy) +  labs(fill = "Depth (m)") +
  scale_fill_gradientn(colours = col_ramp(20)) +
  ggnewscale::new_scale("fill") +
  geom_sf(data = coast, stroke = 0.05, fill = "light yellow", colour = "grey 60") +
  guides(alpha= "none") +
  ylab("")+xlab("") + 
  theme(axis.text.x = element_text(angle = 90))


hp <- base_map +
  geom_sf(data = all_effort_lines, stroke = 0.25, aes(colour = factor(year)))+
  scale_colour_manual(name = "Effort in year", values = c("pink", "grey 40")) +
  ggnewscale::new_scale_colour()+
  geom_sf(data = ap_sf, stroke = 0.01, alpha = 0.5, aes(colour = factor(year), size = Count)) +#
  scale_colour_manual("Sightings in year", values = c("red", "black")) +
  scale_size_manual(values = c(1.5,2,3)) +
  coord 
   # facet_wrap(~month_abb, drop = F)
  # annotation_custom(leg1Grob, xmin=-124.5, xmax=-124.95, ymin=47.9, ymax=48.1) +
hp +
  ggtitle(paste0("CeMoRe seasonal ", sp, " sightings"), subtitle = paste0("To ", survey_title)) +
  facet_wrap(~factor(season, levels = c("Winter", "Spring", "Summer", "Fall")), drop = F)
hp +
 ggtitle(paste0("CeMoRe monthly ", sp, " sightings"), subtitle = paste0("To ", survey_title)) +
 facet_wrap(~month_abb, drop = F)


```

# Harbour Porpoise sighting distance histograms

```{r hp-hist}
source("R/3 dist_hist.R")
no_ret <- all_ap_sf %>% dplyr::filter(!is.na(Reticle))
bins = 80
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 70
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 60
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 50
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 40
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 30
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 20
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 10
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
plot_hist(all_ap_sf, sp, T, n_bins = 40) + ggtitle(label = "All HP sightings")
# plot_hist(no_ret, sp, T, n_bins = 40) + ggtitle(label = "Only reticle HP sightings")

```


# Compare Oct 2020 with Oct 2021
```{r oct-hp-sgt}
oct_hp <- ap_sf %>% filter(month == 10)
oct_lines <- all_effort_lines %>% filter(month == 10)

# # to size symbols by count
# oct_hp <- oct_hp %>% mutate(Count =case_when(
#   BestNumber == 1 ~ "1",
#   BestNumber %in% c(2:5) ~ "2:5",
#   BestNumber >5 ~ ">5"
# ) %>% factor(levels = c("1", "2:5", ">5")))

# coord <- ggplot2::coord_sf(xlim = c(-125.4, -123), ylim = c(48.2, 49.44), crs = sf::st_crs(4326)) 

base_map + 
  geom_sf(data = oct_lines, stroke = 0.25, colour = "grey 40")+
  geom_sf(data = oct_hp, stroke = 0.01, alpha = 0.5, aes(size = Count)) +#
  scale_size_manual(values = c(1.5,2,3)) +
  ggtitle(paste0("CeMoRe survey ", sp, " sightings Oct 2020 vs Oct 2021 ")) +
  # annotation_custom(leg1Grob, xmin=-124.8, xmax=-124.95, ymin=47.9, ymax=48.1) +
  coord +
  facet_wrap(~year, drop = F)

```

## Plot Humpback signtings
```{r hw, echo=FALSE}
all_ap_sf %<>% mutate(Count =case_when(
  BestNumber == 1 ~ "1",
  BestNumber %in% c(2:5) ~ "2:5",
  BestNumber >5 ~ ">5"
) %>% factor(levels = c("1", "2:5", ">5")))

sp <- "Humpback"
ap_sf <- all_ap_sf %>% filter(Species %like% sp)
ap_sf$Species %<>% droplevels()
# to order legend symbols consistently
sp <- unique(c(levels(ap_sf$Species)))

base_map <- ggplot() +
  geom_raster(aes(x=x,y=y,fill = z), data = bathy) +  labs(fill = "Depth (m)") +
  scale_fill_gradientn(colours = col_ramp(20)) +
  ggnewscale::new_scale("fill") +
  geom_sf(data = coast, stroke = 0.05, fill = "light yellow", colour = "grey 60") +
  guides(alpha= "none") +
  ylab("")+xlab("") + 
  theme(axis.text.x = element_text(angle = 90))


hw <- base_map +
  geom_sf(data = all_effort_lines, stroke = 0.25, aes(colour = factor(year)))+
  scale_colour_manual(name = "Effort in year", values = c("pink", "grey 40")) +
  ggnewscale::new_scale_colour()+
  geom_sf(data = ap_sf, stroke = 0.01, alpha = 0.5, aes(colour = factor(year), size = Count)) +#
  scale_colour_manual("Sightings in year", values = c("red", "black")) +
  scale_size_manual(values = c(1.5,2,3)) +
  coord 
   # facet_wrap(~month_abb, drop = F)
  # annotation_custom(leg1Grob, xmin=-124.5, xmax=-124.95, ymin=47.9, ymax=48.1) +
hw +
  ggtitle(paste0("CeMoRe seasonal ", sp, " sightings"), subtitle = paste0("To ", survey_title)) +
  facet_wrap(~factor(season, levels = c("Winter", "Spring", "Summer", "Fall")), drop = F)
hw +
 ggtitle(paste0("CeMoRe monthly ", sp, " sightings"), subtitle = paste0("To ", survey_title)) +
 facet_wrap(~month_abb, drop = F)


```
# Humpback sighting distance histograms

```{r hw-hist}
source("R/3 dist_hist.R")
no_ret <- all_ap_sf %>% dplyr::filter(!is.na(Reticle))
bins = 80
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 70
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 60
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 50
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 40
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 30
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 20
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
bins = 10
plot_hist(all_ap_sf, sp, F, n_bins = bins) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, F, n_bins = bins) + ggtitle(label = "Only reticle HP sightings")
plot_hist(all_ap_sf, sp, T, n_bins = 40) + ggtitle(label = "All HW sightings")
# plot_hist(no_ret, sp, T, n_bins = 40) + ggtitle(label = "Only reticle HP sightings")


```


# Compare Oct 2020 with Oct 2021
```{r oct-hw-sgt}
oct_hW <- ap_sf %>% filter(month == 10)
oct_lines <- all_effort_lines %>% filter(month == 10)

# # to size symbols by count
# oct_hp <- oct_hp %>% mutate(Count =case_when(
#   BestNumber == 1 ~ "1",
#   BestNumber %in% c(2:5) ~ "2:5",
#   BestNumber >5 ~ ">5"
# ) %>% factor(levels = c("1", "2:5", ">5")))

# coord <- ggplot2::coord_sf(xlim = c(-125.4, -123), ylim = c(48.2, 49.44), crs = sf::st_crs(4326)) 

base_map + 
  geom_sf(data = oct_lines, stroke = 0.25, colour = "grey 40")+
  geom_sf(data = oct_hW, stroke = 0.01, alpha = 0.5, aes(size = Count)) +#
  scale_size_manual(values = c(1.5,2,3)) +
  ggtitle(paste0("CeMoRe survey ", sp, " sightings Oct 2020 vs Oct 2021 ")) +
  # annotation_custom(leg1Grob, xmin=-124.8, xmax=-124.95, ymin=47.9, ymax=48.1) +
  coord +
  facet_wrap(~year, drop = F)

```



